blank_issues_enabled: false
contact_links:
  - name: ğŸ“š Documentation
    url: https://sidebase.io/nuxt-auth
    about: Check the documentation for usage of nuxt-auth!
  - name: â­ Other projects
    url: https://sidebase.io
    about: Supercharge your Nuxt application with more of our projects!
