name: nodejs CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.14.2
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8

      # Install locked dependencies and prepare types
      - run: pnpm i
      - run: pnpm dev:prepare

      # start dev-app and curl from it
      - run: "timeout 240 pnpm dev & (sleep 200 && curl --fail localhost:3000)"

      # Check if build and package artifacts can still be generated
      - run: pnpm prepack

      # Check linting and typing
      - run: pnpm lint
      - run: pnpm typecheck

      # Check building
      - run: pnpm build:module
      - run: pnpm build:playground

      # start prod-app and curl from it
      - run: "timeout 240 pnpm start:playground & (sleep 200 && curl --fail localhost:3000)"
