name: nodejs CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VER: 18.19.1
  CI: true

jobs:
  test-module:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VER }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VER }}

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8

      # Install deps and prepare types
      - run: pnpm i
      - run: pnpm dev:prepare

      # Check if build and package artifacts can still be generated
      - run: pnpm prepack

      # Check linting and typing
      - run: pnpm lint
      - run: pnpm typecheck

      # Check building
      - run: pnpm build

  test-playground-local:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./playground-local

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VER }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VER }}

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8

      # Install deps
      - run: pnpm i

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      # Check building
      - run: pnpm build

      - name: Run Playwright tests using Vitest
        run: pnpm test:e2e

  test-playground-refresh:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./playground-refresh
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VER }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VER }}

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8

      # Install deps
      - run: pnpm i

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      # Check building
      - run: pnpm build

      - name: Run Playwright tests using Vitest
        run: pnpm test:e2e

  test-playground-authjs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./playground-authjs
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VER }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VER }}

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8

      # Install deps
      - run: pnpm i

      # Check building
      - run: pnpm build

      # start prod-app and curl from it
      - run: "timeout 60 pnpm start & (sleep 45 && curl --fail localhost:$PORT)"
        env:
          AUTH_ORIGIN: "http://localhost:3001"
          PORT: 3001
